# Generated by Django X on YYYY-MM-DD HH:MM

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='question_files/', verbose_name='Upload JSON/CSV file'),
        ),
    ]

